export enum ErrorCode {
  UNKNOWN = 999,
  EMAIL_ALREADY_USED = 1,
  AUTH_TOKEN_INVALID_REFRESH_TOKEN = 2,
  AUTH_ROLE_INVALID = 3,
  AUTH_INVALID_BASIC_AUTH_CREDENTIALS = 4,
  USER_NOT_FOUND = 5,
  PASSWORD_NOT_CORRECT = 6,
  INVALID_SIGNATURE = 7
}
